### ISSUE TITLE
please increase versionCode

### ISSUE THREAD

**Issue by IzzySoft** [dubrowgn/wattz#1]
`versionCode`for your latest release is still set to `1`. Android uses `versionCode` to tell versions apart, [F-Droid](https://gitlab.com/fdroid/rfp/-/issues/2195) will require you to have it increased or it cannot update.

Oh, F-Droid will require Fastlane Metadata, too. I'll prepare a PR to provide you with a starter package.

**Comment by dubrowgn** [comment]
Thanks, I wasn't aware there were two version fields. Fixed in cb51c6e11c931da3b5caee8cb41f89307adfce20.

**Comment by IzzySoft** [comment]
Great, thanks! Yeah, thw one mentioned here is what Android uses internally (the one "for the machine"). The one you've been aware of is the one "for the human" :wink: `versionCode` is an integer. You can use it as release counter if you wish (so just increasing it by 1 on each release), or to indicate the release time (like `202209082300`), or have it match the "other one" (e.g. `1001002` for version 1.1.2) – the only important thing is that it must be increased and never decreased.
