### ISSUE TITLE
DateTime since put on charging

### ISSUE THREAD

**Issue by nata1993** [dubrowgn/wattz#10]
DateTime element showing date and time when phone was put on charge is constantly being refreshed to "now" while phone is being charged.

Running watt v1.7.

**Comment by dubrowgn** [comment]
I've been looking at different ways to solve this over the past few days. A working solution is actually quite complicated, so I may end up removing the feature for now.

**Comment by dubrowgn** [comment]
https://github.com/dubrowgn/wattz/commit/45e16a460060e183bd1e940eb620a645a53552f9 fixes this by making the StatusService own "ChargingSince". As long as the indicator is present, it will know when the phone is plugged or unplugged.

Available: https://github.com/dubrowgn/wattz/releases/tag/v1.8
