### ISSUE TITLE
Charging direction indication

### ISSUE THREAD

**Issue by harrischrisa** [dubrowgn/wattz#23]
I cleared all storage and found the app showed that the device was indicating  Charging when NOT plugged in and Power and Current readings were negative. In Settings the Invert Current is turned off and the Preview is positive.  (Current Units need to be set a mA). Everything is reversed when charging

If I turn on Invert Current the preview is negative. The the Charging indicator is correct BUT Power and Current are positive.  When plugged-in the Charging indicator is correct but Power and Current are negative.

If seems that the charging indicator is out of sync with the Power and Current indicators. Can this be fixed?

BTW phone is a realme X2 with Android 11.

**Comment by dubrowgn** [comment]
This is expected behavior, but I see how it can be confusing. The preview shows raw values (coming from the OS), not display values (displayed in the app). In the main view, power numbers should be positive when not plugged-in.

I considered showing display values in the settings view, but knowing the actual raw values can be very useful for debugging these kinds of device issues. Maybe it just adds more confusion than it's worth?

**Comment by harrischrisa** [comment]
Hi

Is this correct? This screenshot is while

[cid:eu.faircode.email.12424]Charging..
The second image is when Not charging.



[cid:eu.faircode.email.12426]


13 Oct 2022 1:17:51 am Dustin Brown ***@***.***>:

**Comment by dubrowgn** [comment]
It doesn't look like any images got attached.

Do you think something like this is less confusing? It avoids any reference to raw battery data.

![settings](https://user-images.githubusercontent.com/1294253/195417103-0450a4db-2e96-4090-b52a-01a6171b8cb6.png)

**Comment by harrischrisa** [comment]
Your new settings looks better.

FYI here are my screenshots

Chris

14 Oct 2022 1:44:46 am Dustin Brown ***@***.***>:

**Comment by dubrowgn** [comment]
The simplified settings view is available in v1.11. I'm going to close this issue with that, but please let me know if you continue to experience problems.

**Comment by harrischrisa** [comment]
Hi

I am running Wattz 1.11 on my phone with no problems. I decided to install it on my Huawei Mediapad M5 tablet. When installing it I get the message "there was a problem while parsing the package". I downloaded the app again and also transfered the app from my phone (which I successfully installed). I also tried an earlier version.

All installations caused the same error.


I have turned on developer option and install from unknown sources.

I can sideload other apps.

Can you suggest what I have to do to install the app?

Regards
Chris

**Comment by dubrowgn** [comment]
Hmm, I'm not sure. If you are installing the apk from this repo, you could try the F-Droid version, or vice versa. The only other thing that comes to mind is maybe trying to build the app for an earlier target version? It *shouldn't* matter though.

**Comment by dubrowgn** [comment]
What version of Android are you running? https://www.gsmarena.com/huawei_mediapad_m5_10-9091.php says the M5 shipped with 8.0 (Oreo). The App requires 9.0 (Pie).

**Comment by harrischrisa** [comment]
Yes it only has version 8 and no further updates available.

I will have to live without the app.

Thanks
Chris

30 Oct 2022 12:29:09 am Dustin Brown ***@***.***>:
