### ISSUE TITLE
since version 1.11 temperature is hanging

### ISSUE THREAD

**Issue by paulle** [dubrowgn/wattz#24]
Since version 1.11 temperature is is no more working for me. It stays always with the same temperature even then the phone is getting hot.
All other values are working fine.

Anndroid12, Sony Xperia 5 III

**Comment by dubrowgn** [comment]
Does it never update, or does it update infrequently? I don't think there is any requirements around update frequency, and I've noticed that temperature can take a relatively long time to update on my devices.

**Comment by paulle** [comment]
It seems never to update, at least not within hours, I tested putting the phone in the fridge for some hours.

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 11. Nov. 2022, 15:56, schrieb Dustin Brown :

**Comment by dubrowgn** [comment]
Hmm, I can reproduce the issue also. The fridge was a good idea.

**Comment by dubrowgn** [comment]
A fix is available in https://github.com/dubrowgn/wattz/releases/tag/v1.12

**Comment by paulle** [comment]
Yes it seems to be fixed now.
Thank you.

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 12. Nov. 2022, 17:53, schrieb Dustin Brown :
