### ISSUE TITLE
Charging information doesn't update

### ISSUE THREAD

**Issue by unterflieger** [dubrowgn/wattz#29]
On Samsung Galaxy S23 Ultra, the charging indicator doesn't change from its initial value (which is "yes"), neither does it show the right wattage. It stays at zero, and the workaround doesn't work either. (Possibly a Samsung only problem, works fine on other devices)

**Comment by dubrowgn** [comment]
Sorry to hear things aren't working out for you. It's difficult to know what's going wrong without looking at the raw battery data, but I can suggest a couple things to try:

1. Samsung phones are known to incorrectly implement the battery API's. You've already tried the work arounds, but it might be worth doubling checking that you are _not_ plugged in while doing this
2. Battery data is updated in a foreground service that is tied to the power indicator notification. It should still work without notification permissions, but it might be worth checking if notification settings are enabled for Wattz.
3. Samsung phones are known for being extremely aggressive at killing/suspending things to save power. It might be worth changing power save (aka battery optimization) in the app settings, and see if that does anything.
4. If you have access to android studio, or adb tools, logcat might give more info (e.g. if the status service is crashing for some reason)

I'd be very interested to hear if any of those help. Maybe I can work around the issue, or at least document it.
