### ISSUE TITLE
Make the app shows notification only in notification bar 

### ISSUE THREAD

**Issue by YuimiLungleng** [dubrowgn/wattz#36]
I wanna hide the notification of the app from the notification drawer.

**Comment by dubrowgn** [comment]
Unfortunately, I don't think this is possible. Android doesn't actually have a way to make status icons, so Wattz abuses a persistent notification to approximate the same thing. As far as I can tell, there isn't a way to hide a notification in the notification drawer without also hiding it in the status bar.

**Comment by YuimiLungleng** [comment]
> Unfortunately, I don't think this is possible. Android doesn't actually have a way to make status icons, so Wattz abuses a persistent notification to approximate the same thing. As far as I can tell, there isn't a way to hide a notification in the notification drawer without also hiding it in the status bar.

Ok I don't know about that, but thanks for replying back and again Thank U for the application.
