### ISSUE TITLE
Temperature Increase(?) and Question

### ISSUE THREAD

**Issue by ooFVenomous** [dubrowgn/wattz#48]
Firstly, your piece of software is very useful. I was always curious about the actual charging amount and not just a time-to-full charge. I came across a TikTok video talking about your app and its usefulness. 

When using the app and not plugged in, I could feel a slight temperature increase that is abnormal. It wasn't getting insanely hot, but warm enough to notice. This might be because I had the Charging Workaround enabled. For reference, I am using the S23 Ultra. 

Now for a question, is the notification bar and Power in the app supposed to show a negative watts number? (It usually shows around -1.5w) When I enable the Charging Workaround, it becomes a positive number but then says I am not charging when I am. I also have the Power Scalar Workaround set to 1000x as that seems to be the only one that shows any number besides 0w.

**Comment by dubrowgn** [comment]
I'm glad you find it useful!

I'm not aware of, or have heard of, any temperature issues with the app so far. I use the app to see how hot my phones is in different situations, and have not noticed any abnormal heating. The 1000X power scalar workaround is pretty normal for Samsung phones. It literally just multiplies the current reported by the `BatteryManager` by 1000, so the setting shouldn't have any kind of impact on actual power or temperatures.

The app is a power _consumption_ indicator, but it is also useful as a power _charging_ indicator (and many people use it for that). If you look at it from the second perspective, the signs look odd, but that wasn't really the original intended use case.

For an S23 Ultra, the correct settings are probably the 1000X power scalar with the charging workaround off.

**Comment by ooFVenomous** [comment]
Thank you. I was curious as it was "marketed" to me as a _charging_ indicator. I'll keep watch on if it has any impact on power or temperature.
