### ISSUE TITLE
Amperage, Watt and and charging not working

### ISSUE THREAD

**Issue by nata1993** [dubrowgn/wattz#8]
Current metering and power metering not working on Samsung Galaxy A52 5G.

Upon putting phone ln charging, the charging text is showing "not charging".
Upon removing phone from charging, app will notify that phone is fully charged despite phone being not fully charged. Push notification constantly saying phone fully charged.

This is with running app v1.4 from F-Droid. There is yet no version 1.5 on F-Droid where problem is claimed to be fixed.

**Comment by dubrowgn** [comment]
Related: https://github.com/dubrowgn/wattz/issues/5

**Comment by dubrowgn** [comment]
I have a pair of work arounds which should address the remaining two issues on Samsung devices, but I'm waiting on a device to test it. Hopefully, I'll have a new build up later today.

**Comment by dubrowgn** [comment]
This should be fixed in v1.6

**Comment by nata1993** [comment]
Compiled v1.7 and everything works as intended now on Samsung Galaxy A52 5G.
