### ISSUE TITLE
How to show watts in status bar?

### ISSUE THREAD

**Issue by anaxonda** [dubrowgn/wattz#9]
Hello,

I've installed the application but do not see how to make it show the watts in the status bar. Running Android 12 (LineageOS).

Is there some setting to enable this?

**Comment by anaxonda** [comment]
Hmm, strange but it just started showing after being installed for some hours.  I guess I can close this issue.

**Comment by dubrowgn** [comment]
Both opening the app and restarting your phone will start the status service. I'm not aware of any way to automatically launch an app or service after installation.

**Comment by anaxonda** [comment]
I did open the app after first installing.
